name: CI
on: [pull_request, push]
jobs:
  format:
    name: formatting check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          component: rustfmt
          profile: minimal
          override: true

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
